[package]
name = "mathematica_examples"
version = "0.1"
lean_version = "leanprover-community/lean:3.32.1"
path = "src"

[dependencies]
mathematica = {git = "https://github.com/rlewis1988/mathematica", rev = "b923b08c35f8533b840822dda2e7f31b6f05234d"}
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "bf0b5df370c0012b5ac936d659d707798d86eb01"}
